version: '3'

services:
  meltano:
    build: .
    ports:
      - "5001:5001"
    environment:
      - MELTANO_ENVIRONMENT=prod
    command: ["invoke", "airflow", "scheduler"]

  airflow-scheduler:
    build: .
    command: invoke airflow scheduler
    expose:
      - 8793
    restart: unless-stopped
    depends_on:
      - meltano

  airflow-webserver:
    build: .
    command: invoke airflow webserver
    expose:
      - 8080
    ports:
      - 8080:8080
    restart: unless-stopped
    depends_on:
      - meltano